# Site settings
title: PLGN
email: hello@plgn.org
url: https://plgn.org
description: "открытая лаборатория для экспериментов и обучения в области искусства и технологий"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: PLGN

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/plgnlab
  - title: notion
    url: https://www.notion.so/PLGN-DATABASE-3981132db6b948b282c7aa3afd02c466
  - title: github
    url: https://github.com/plgn

# Build settings
markdown: kramdown
permalink: pretty
